#!/bin/bash
# Usage: script/brew-local <name> <version> [<gh-project>]
#
set -e

this=`dirname $0`

brew_name="${1?}"
url="${2?}"
version=$(basename $url | awk -F'-' '{print $2}' | cut -d'.' -f1,2,3)

if ! type -p hub >/dev/null; then
  "ERROR: You have to install hub to proceed." >&2
  exit 1
fi

checksum="$(curl -fsSL "$url" | shasum -a 256 -b | awk '{print $1}')"

if [ -z "$checksum" ]; then
  echo "ERROR: calculating the checksum failed for $url" >&2
  exit 1
fi

git fetch -q --unshallow origin master 2>/dev/null || git fetch -q origin master

branch="${brew_name}-${version}"
git checkout -q -B "$branch" origin/master

formula="${brew_name}.rb"
sed -i.bak -E "
  s!^(  url ).+!\\1\"${url}\"!
  s!^(  sha256 ).+!\\1\"${checksum}\"!
" "$formula"
rm -f "${formula}.bak"

git commit -m "${brew_name} ${version#v}" -- "$formula"
git push -u origin "$branch"
git checkout -q -

